version: '3.6'

volumes:
  migrations:

services:
  manager:
    build:
      context: .
      dockerfile: Dockerfile-manager
    volumes:
      - ./volume:/usr/src/app/volume
    ports:
      - 8000:8000

  mqtt-client:
    depends_on:
      - manager
    build:
      context: .
      dockerfile: Dockerfile-mqttclient